const DummyData = [{'name': 'Alice', 
'company': 'Apple', 
'phone': 39465928364, 
'email': 'Alice@gmail.com', 
'notes': 'Meeting tomorrow', 
'contractWorth': 2300}, 
{'name': 'Tom', 
'company': 'IBM', 
'phone': 35908740237, 
'email': 'Tom@gmail.com', 
'notes': 'A new client to talk too', 
'contractWorth': 1100}, 
{'name': 'Sam', 
'company': 'Hello World', 
'phone': 102437589, 
'email': 'Sam@gmail.com', 
'notes': 'Building a website with them.', 
'contractWorth': 5600}] 

export default DummyData